export const TestIds = {
  EMPTY_DIV: 'EmptyDiv',
  WAITING_SPINNER: 'WAITING_SPINNER',
  FOOTER: 'Footer',
  POPUP: 'Popup',
  PAGE_HOME: 'PAGE_HOME',
  PAGE_HOME_DISPLAY_NAME: 'PAGE_HOME_DISPLAY_NAME',
  PAGE_MAIN: 'PAGE_MAIN',
  PANEL_HEADER: 'PANEL_HEADER',
} as const;
