version: '3.6'
services:
  app:
    image: ${REPOSITORY_URI}
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - REACT_APP_API_HOST=${REACT_APP_API_HOST}
        - REACT_APP_NODE_ENV=${REACT_APP_NODE_ENV}
        - REACT_APP_HOST=${REACT_APP_HOST}
        - SPRING_PROFILE=${SPRING_PROFILE}
    container_name: app
    ports:
      - 8080:8080
    tty: true
  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "jitwin_dev"
    volumes:
      - "./docker/db/data:/var/lib/postgresql/data"
      - "./docker/db/initdb:/docker-entrypoint-initdb.d"
