name: unit tests on main repos
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  testFrontend:
    runs-on: node:16-alpine
    steps:
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
      run: |
        cd ./web
        yarn install
        yarn lint
        yarn test:ci

